version: "3"

services:
    db:
        container_name: database
        image: postgres
        environment:
            - POSTGRES_DB=auth
            - POSTGRES_USER=hanko
            - POSTGRES_PASSWORD=postgress_password
        ports:
            - 6032:5432
        healthcheck:
            test: pg_isready -U hanko -d auth
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 30s

    hanko-migrate:
        image: ghcr.io/teamhanko/hanko:latest
        container_name: hanko-migrate
        command: --config /config/config.yaml migrate up
        restart: on-failure
        volumes:
            - .config.yaml:/config/config.yaml:ro
        depends_on:
            db:
                condition: service_healthy

    hanko:
        image: ghcr.io/teamhanko/hanko:latest
        container_name: hanko
        command: --config /config/config.yaml serve all
        restart: unless-stopped
        ports:
            - "7000:8000" # public
            - "7001:8001" # admin
        volumes:
            - .config.yaml:/config/config.yaml:ro
        depends_on:
            hanko-migrate:
                condition: service_completed_successfully

    mailserver:
        image: maildev/maildev:latest
        container_name: mailserver
        restart: always
        ports:
            - "5000:80" # web interface
            - "5025:25" # smtp server
        environment:
            - MAILDEV_WEB_PORT=80
            - MAILDEV_SMTP_PORT=25
        logging:
            driver: "json-file"
            options:
                max-size: "1m"
